import type { Asset, RepairRecord } from "./types";

const AUG = (day: number, hour = 16) =>
  new Date(Date.UTC(2026, 7, day, hour, 0, 0)).toISOString();

export const SEED_ASSETS: Asset[] = [
  // 9 Unitree Go2 — 5 Pro, 4 Edu
  {
    id: "go2-01",
    kind: "robot",
    name: "GO2-01",
    callsign: "Red",
    imageUrl: "/robots/go2-red.jpg",
    model: "Unitree Go2 Pro",
    platform: "go2",
    serial: "GO2P-8841-01",
    status: "ready",
    condition: "",
    notes: "Primary demo unit. Full gait set verified after last firmware flash.",
    lastChecked: AUG(31, 14),
  },
  {
    id: "go2-02",
    kind: "robot",
    name: "GO2-02",
    callsign: "Blue",
    imageUrl: "/robots/go2-blue.jpg",
    model: "Unitree Go2 Pro",
    platform: "go2",
    serial: "GO2P-8841-02",
    status: "ready",
    condition: "",
    notes: "Outdoor unit. Mud guards cleaned 8/30.",
    lastChecked: AUG(30, 18),
  },
  {
    id: "go2-03",
    kind: "robot",
    name: "GO2-03",
    callsign: "Black",
    imageUrl: "/robots/go2-black.jpg",
    model: "Unitree Go2 Pro",
    platform: "go2",
    serial: "GO2P-8841-03",
    status: "limited",
    condition:
      "Front-left hip joint gets noisy after ~20 minutes. Indoor demos only; no stairs.",
    notes: "Parts ordered for hip actuator. Keep off the obstacle course.",
    lastChecked: AUG(31, 11),
  },
  {
    id: "go2-04",
    kind: "robot",
    name: "GO2-04",
    callsign: "White",
    imageUrl: "/robots/go2-white.jpg",
    model: "Unitree Go2 Pro",
    platform: "go2",
    serial: "GO2P-8841-04",
    status: "ready",
    condition: "",
    notes: "Spare for classroom. Calibration saved on the lab laptop.",
    lastChecked: AUG(29, 15),
  },
  {
    id: "go2-05",
    kind: "robot",
    name: "GO2-05",
    callsign: "Halo",
    imageUrl: "/robots/go2-edu-halo.jpg",
    model: "Unitree Go2 Edu",
    platform: "go2",
    serial: "GO2E-9102-05",
    status: "ready",
    condition: "",
    notes: "Edu compute payload installed. ROS 2 workspace is current.",
    lastChecked: AUG(31, 9),
  },
  {
    id: "go2-06",
    kind: "robot",
    name: "GO2-06",
    callsign: "Sable",
    imageUrl: "/robots/go2-edu-sable.jpg",
    model: "Unitree Go2 Edu",
    platform: "go2",
    serial: "GO2E-9102-06",
    status: "limited",
    condition:
      "Lidar returns go sparse in bright sunlight. Fine indoors; avoid noon outdoor nav.",
    notes: "Waiting on a replacement optical window.",
    lastChecked: AUG(28, 17),
  },
  {
    id: "go2-07",
    kind: "robot",
    name: "GO2-07",
    callsign: "Volt",
    imageUrl: "/robots/go2-edu-volt.jpg",
    model: "Unitree Go2 Edu",
    platform: "go2",
    serial: "GO2E-9102-07",
    status: "down",
    condition:
      "Will not boot. Power board suspected — unit is on the bench, do not assign.",
    notes: "Ticket with Unitree support #4418. IMU also failed POST last week.",
    lastChecked: AUG(27, 13),
  },
  {
    id: "go2-08",
    kind: "robot",
    name: "GO2-08",
    callsign: "Orange",
    imageUrl: "/robots/go2-orange.jpg",
    model: "Unitree Go2 Pro",
    platform: "go2",
    serial: "GO2P-8841-08",
    status: "ready",
    condition: "",
    notes: "Newest Pro. Still on factory gait params.",
    lastChecked: AUG(31, 10),
  },
  {
    id: "go2-09",
    kind: "robot",
    name: "GO2-09",
    callsign: "Kite",
    imageUrl: "/robots/go2-edu-kite.jpg",
    model: "Unitree Go2 Edu",
    platform: "go2",
    serial: "GO2E-9102-09",
    status: "ready",
    condition: "",
    notes: "Teaching unit. Student accounts wiped after each lab.",
    lastChecked: AUG(30, 12),
  },

  // 2 Unitree G1 humanoids
  {
    id: "g1-01",
    kind: "robot",
    name: "G1-01",
    callsign: "Rowan",
    imageUrl: "/robots/g1-rowan.jpg",
    model: "Unitree G1",
    platform: "g1",
    serial: "G1-1104-01",
    status: "ready",
    condition: "",
    notes: "Balance and walk verified on the lab floor this morning.",
    lastChecked: AUG(31, 8),
  },
  {
    id: "g1-02",
    kind: "robot",
    name: "G1-02",
    callsign: "Wren",
    imageUrl: "/robots/g1-wren.jpg",
    model: "Unitree G1",
    platform: "g1",
    serial: "G1-1104-02",
    status: "limited",
    condition:
      "Right wrist encoder drifts after ~15 minutes. Avoid precision grasping and handshakes.",
    notes: "Can still walk and demo upper-body motion. Encoder swap scheduled.",
    lastChecked: AUG(30, 19),
  },

  // Go2 batteries
  {
    id: "bat-01",
    kind: "battery",
    name: "BAT-01",
    model: "Go2 8000 mAh",
    platform: "go2",
    serial: "BT-8000-01",
    status: "ready",
    condition: "",
    notes: "",
    lastChecked: AUG(31, 14),
    assignedToId: "go2-01",
    cycles: 42,
  },
  {
    id: "bat-02",
    kind: "battery",
    name: "BAT-02",
    model: "Go2 8000 mAh",
    platform: "go2",
    serial: "BT-8000-02",
    status: "ready",
    condition: "",
    notes: "",
    lastChecked: AUG(30, 18),
    assignedToId: "go2-02",
    cycles: 38,
  },
  {
    id: "bat-03",
    kind: "battery",
    name: "BAT-03",
    model: "Go2 8000 mAh",
    platform: "go2",
    serial: "BT-8000-03",
    status: "limited",
    condition: "Drops to 20% quickly under load. Use only for short indoor runs.",
    notes: "Cycle count is high. Retire after this month if it keeps sagging.",
    lastChecked: AUG(31, 11),
    assignedToId: "go2-03",
    cycles: 187,
  },
  {
    id: "bat-04",
    kind: "battery",
    name: "BAT-04",
    model: "Go2 15000 mAh",
    platform: "go2",
    serial: "BT-15000-04",
    status: "ready",
    condition: "",
    notes: "Long-run pack. Keep for outdoor sessions.",
    lastChecked: AUG(29, 15),
    assignedToId: "go2-04",
    cycles: 21,
  },
  {
    id: "bat-05",
    kind: "battery",
    name: "BAT-05",
    model: "Go2 8000 mAh",
    platform: "go2",
    serial: "BT-8000-05",
    status: "ready",
    condition: "",
    notes: "",
    lastChecked: AUG(31, 9),
    assignedToId: "go2-05",
    cycles: 55,
  },
  {
    id: "bat-06",
    kind: "battery",
    name: "BAT-06",
    model: "Go2 8000 mAh",
    platform: "go2",
    serial: "BT-8000-06",
    status: "ready",
    condition: "",
    notes: "On the charging rack.",
    lastChecked: AUG(31, 16),
    cycles: 60,
  },
  {
    id: "bat-07",
    kind: "battery",
    name: "BAT-07",
    model: "Go2 8000 mAh",
    platform: "go2",
    serial: "BT-8000-07",
    status: "down",
    condition: "Swollen case. Do not charge. Bagged and marked for disposal.",
    notes: "Pulled from Volt before the boot failure.",
    lastChecked: AUG(27, 13),
    cycles: 210,
  },
  {
    id: "bat-08",
    kind: "battery",
    name: "BAT-08",
    model: "Go2 15000 mAh",
    platform: "go2",
    serial: "BT-15000-08",
    status: "ready",
    condition: "",
    notes: "",
    lastChecked: AUG(31, 10),
    assignedToId: "go2-08",
    cycles: 12,
  },
  {
    id: "bat-09",
    kind: "battery",
    name: "BAT-09",
    model: "Go2 8000 mAh",
    platform: "go2",
    serial: "BT-8000-09",
    status: "ready",
    condition: "",
    notes: "",
    lastChecked: AUG(30, 12),
    assignedToId: "go2-09",
    cycles: 33,
  },
  {
    id: "bat-10",
    kind: "battery",
    name: "BAT-10",
    model: "Go2 8000 mAh",
    platform: "go2",
    serial: "BT-8000-10",
    status: "limited",
    condition: "Charge port is loose. Seat it fully or it will not take a charge.",
    notes: "Spare on the rack. Tape a note on the latch.",
    lastChecked: AUG(28, 10),
    cycles: 94,
  },
  {
    id: "bat-11",
    kind: "battery",
    name: "BAT-11",
    model: "Go2 8000 mAh",
    platform: "go2",
    serial: "BT-8000-11",
    status: "ready",
    condition: "",
    notes: "Hot spare for demos.",
    lastChecked: AUG(31, 15),
    cycles: 8,
  },

  // G1 batteries
  {
    id: "bat-g1-01",
    kind: "battery",
    name: "BAT-G1-01",
    model: "G1 battery pack",
    platform: "g1",
    serial: "G1B-01",
    status: "ready",
    condition: "",
    notes: "",
    lastChecked: AUG(31, 8),
    assignedToId: "g1-01",
    cycles: 19,
  },
  {
    id: "bat-g1-02",
    kind: "battery",
    name: "BAT-G1-02",
    model: "G1 battery pack",
    platform: "g1",
    serial: "G1B-02",
    status: "ready",
    condition: "",
    notes: "",
    lastChecked: AUG(30, 19),
    assignedToId: "g1-02",
    cycles: 24,
  },
  {
    id: "bat-g1-03",
    kind: "battery",
    name: "BAT-G1-03",
    model: "G1 battery pack",
    platform: "g1",
    serial: "G1B-03",
    status: "limited",
    condition: "Reports 100% but voltage sags under walk. Keep as a warm-up pack only.",
    notes: "BMS logs saved on the G1 laptop.",
    lastChecked: AUG(29, 11),
    cycles: 61,
  },

  // Chargers
  {
    id: "chg-01",
    kind: "charger",
    name: "CHG-01",
    model: "Go2 charger 54V",
    platform: "go2",
    serial: "CH-54-01",
    status: "ready",
    condition: "",
    notes: "Bay A wall.",
    lastChecked: AUG(31, 14),
  },
  {
    id: "chg-02",
    kind: "charger",
    name: "CHG-02",
    model: "Go2 charger 54V",
    platform: "go2",
    serial: "CH-54-02",
    status: "ready",
    condition: "",
    notes: "Bay A wall.",
    lastChecked: AUG(30, 18),
  },
  {
    id: "chg-03",
    kind: "charger",
    name: "CHG-03",
    model: "Go2 charger 54V",
    platform: "go2",
    serial: "CH-54-03",
    status: "limited",
    condition: "Fan is loud and the brick runs hot. Use on a metal cart, not under a desk.",
    notes: "Still charges to full in a normal window.",
    lastChecked: AUG(28, 16),
  },
  {
    id: "chg-04",
    kind: "charger",
    name: "CHG-04",
    model: "Go2 charger 54V",
    platform: "go2",
    serial: "CH-54-04",
    status: "ready",
    condition: "",
    notes: "Classroom cart.",
    lastChecked: AUG(29, 15),
  },
  {
    id: "chg-05",
    kind: "charger",
    name: "CHG-05",
    model: "Go2 charger 54V",
    platform: "go2",
    serial: "CH-54-05",
    status: "down",
    condition: "No output. Fuse popped twice. Tagged and unplugged.",
    notes: "Do not try another fuse until we inspect the cable.",
    lastChecked: AUG(26, 12),
  },
  {
    id: "chg-06",
    kind: "charger",
    name: "CHG-06",
    model: "Go2 charger 54V",
    platform: "go2",
    serial: "CH-54-06",
    status: "ready",
    condition: "",
    notes: "Travel kit.",
    lastChecked: AUG(31, 10),
  },
  {
    id: "chg-g1-01",
    kind: "charger",
    name: "CHG-G1-01",
    model: "G1 charger",
    platform: "g1",
    serial: "G1C-01",
    status: "ready",
    condition: "",
    notes: "Humanoid bench.",
    lastChecked: AUG(31, 8),
  },
  {
    id: "chg-g1-02",
    kind: "charger",
    name: "CHG-G1-02",
    model: "G1 charger",
    platform: "g1",
    serial: "G1C-02",
    status: "ready",
    condition: "",
    notes: "Spare in the G1 case.",
    lastChecked: AUG(29, 9),
  },

  // Remotes
  {
    id: "rc-01",
    kind: "remote",
    name: "RC-01",
    model: "Go2 remote",
    platform: "go2",
    serial: "RC-GO2-01",
    status: "ready",
    condition: "",
    notes: "Paired to Red.",
    lastChecked: AUG(31, 14),
    assignedToId: "go2-01",
  },
  {
    id: "rc-02",
    kind: "remote",
    name: "RC-02",
    model: "Go2 remote",
    platform: "go2",
    serial: "RC-GO2-02",
    status: "ready",
    condition: "",
    notes: "Paired to Blue.",
    lastChecked: AUG(30, 18),
    assignedToId: "go2-02",
  },
  {
    id: "rc-03",
    kind: "remote",
    name: "RC-03",
    model: "Go2 remote",
    platform: "go2",
    serial: "RC-GO2-03",
    status: "limited",
    condition: "Left stick has drift. Recenter before every walk or it veers.",
    notes: "Paired to Black. Recalibrate in the Unitree app if students use it.",
    lastChecked: AUG(31, 11),
    assignedToId: "go2-03",
  },
  {
    id: "rc-04",
    kind: "remote",
    name: "RC-04",
    model: "Go2 remote",
    platform: "go2",
    serial: "RC-GO2-04",
    status: "ready",
    condition: "",
    notes: "",
    lastChecked: AUG(29, 15),
    assignedToId: "go2-04",
  },
  {
    id: "rc-05",
    kind: "remote",
    name: "RC-05",
    model: "Go2 remote",
    platform: "go2",
    serial: "RC-GO2-05",
    status: "ready",
    condition: "",
    notes: "",
    lastChecked: AUG(31, 9),
    assignedToId: "go2-05",
  },
  {
    id: "rc-06",
    kind: "remote",
    name: "RC-06",
    model: "Go2 remote",
    platform: "go2",
    serial: "RC-GO2-06",
    status: "down",
    condition: "Will not pair. Bluetooth chip likely dead.",
    notes: "Tried factory reset. Still invisible to the app.",
    lastChecked: AUG(27, 10),
  },
  {
    id: "rc-07",
    kind: "remote",
    name: "RC-07",
    model: "Go2 remote",
    platform: "go2",
    serial: "RC-GO2-07",
    status: "ready",
    condition: "",
    notes: "Spare in the travel case.",
    lastChecked: AUG(31, 10),
  },
  {
    id: "rc-08",
    kind: "remote",
    name: "RC-08",
    model: "Go2 remote",
    platform: "go2",
    serial: "RC-GO2-08",
    status: "ready",
    condition: "",
    notes: "",
    lastChecked: AUG(30, 12),
    assignedToId: "go2-09",
  },
  {
    id: "rc-g1-01",
    kind: "remote",
    name: "RC-G1-01",
    model: "G1 remote",
    platform: "g1",
    serial: "RC-G1-01",
    status: "ready",
    condition: "",
    notes: "Paired to Rowan.",
    lastChecked: AUG(31, 8),
    assignedToId: "g1-01",
  },
  {
    id: "rc-g1-02",
    kind: "remote",
    name: "RC-G1-02",
    model: "G1 remote",
    platform: "g1",
    serial: "RC-G1-02",
    status: "limited",
    condition: "L1 bumper sticks. Tap it twice if a gait command does not take.",
    notes: "Paired to Wren.",
    lastChecked: AUG(30, 19),
    assignedToId: "g1-02",
  },
];

const JUL = (day: number, hour = 16) =>
  new Date(Date.UTC(2026, 6, day, hour, 0, 0)).toISOString();

export const SEED_REPAIRS: RepairRecord[] = [
  {
    id: "rep-red-1",
    assetId: "go2-01",
    openedAt: JUL(28, 11),
    resolvedAt: AUG(2, 16),
    openedStatus: "limited",
    title: "Ankle calibration after a hard stop",
    detail: "Right-rear ankle felt soft on the demo floor.",
    resolution: "Recalibrated in the Unitree app. Walked a full loop, green.",
  },
  {
    id: "rep-blue-1",
    assetId: "go2-02",
    openedAt: AUG(8, 18),
    resolvedAt: AUG(11, 10),
    openedStatus: "limited",
    title: "Water in the foot wells after a rain demo",
    detail: "Outdoor unit came back dripping. Indoor only until dry.",
    resolution: "Dried overnight, checked connectors, no corrosion.",
  },
  {
    id: "rep-black-pad",
    assetId: "go2-03",
    openedAt: AUG(4, 9),
    resolvedAt: AUG(7, 15),
    openedStatus: "limited",
    title: "Loose rear foot pad",
    detail: "Pad was walking off the foot on carpet.",
    resolution: "Replaced the pad and thread-locked the screw.",
  },
  {
    id: "rep-black-hip",
    assetId: "go2-03",
    openedAt: AUG(22, 14),
    openedStatus: "limited",
    title: "Front-left hip joint noisy after ~20 minutes",
    detail: "Indoor demos only; no stairs. Parts ordered for the hip actuator.",
  },
  {
    id: "rep-white-1",
    assetId: "go2-04",
    openedAt: JUL(18, 13),
    resolvedAt: JUL(19, 11),
    openedStatus: "down",
    title: "App would not connect on 5 GHz",
    detail: "Classroom Wi-Fi blocked the dongle.",
    resolution: "Moved the laptop to 2.4 GHz. Reconnected first try.",
  },
  {
    id: "rep-halo-1",
    assetId: "go2-05",
    openedAt: AUG(1, 10),
    resolvedAt: AUG(5, 12),
    openedStatus: "limited",
    title: "Edu payload USB port flaky",
    detail: "Compute box dropped off mid-lab.",
    resolution: "Replaced the USB cable and reseated the payload.",
  },
  {
    id: "rep-sable-lidar",
    assetId: "go2-06",
    openedAt: AUG(20, 9),
    openedStatus: "limited",
    title: "Lidar sparse in bright sunlight",
    detail: "Fine indoors; avoid noon outdoor nav. Waiting on a replacement optical window.",
  },
  {
    id: "rep-volt-imu",
    assetId: "go2-07",
    openedAt: AUG(12, 11),
    resolvedAt: AUG(16, 17),
    openedStatus: "down",
    title: "IMU failed POST",
    detail: "Would not finish boot after a student lab.",
    resolution: "Reseated the IMU cable. Booted clean for four days, then died again.",
  },
  {
    id: "rep-volt-board",
    assetId: "go2-07",
    openedAt: AUG(24, 13),
    openedStatus: "down",
    title: "Will not boot. Power board suspected",
    detail: "On the bench. Ticket with Unitree support #4418.",
  },
  {
    id: "rep-orange-1",
    assetId: "go2-08",
    openedAt: AUG(20, 15),
    resolvedAt: AUG(21, 9),
    openedStatus: "limited",
    title: "Factory gait too aggressive for indoor halls",
    detail: "Clipped a doorframe on first walk.",
    resolution: "Retuned gait params. Still on a conservative indoor profile.",
  },
  {
    id: "rep-rowan-1",
    assetId: "g1-01",
    openedAt: AUG(18, 8),
    resolvedAt: AUG(25, 16),
    openedStatus: "limited",
    title: "Knee servo overheat after long standing demo",
    detail: "Right knee hit thermal limit.",
    resolution: "Cooled, re-greased, and verified a 20-minute stand.",
  },
  {
    id: "rep-wren-finger",
    assetId: "g1-02",
    openedAt: AUG(10, 14),
    resolvedAt: AUG(14, 11),
    openedStatus: "limited",
    title: "Left finger tendon slack",
    detail: "Grip would not close fully.",
    resolution: "Tensioned the tendon. Handshake demo is fine.",
  },
  {
    id: "rep-wren-wrist",
    assetId: "g1-02",
    openedAt: AUG(26, 19),
    openedStatus: "limited",
    title: "Right wrist encoder drift after ~15 minutes",
    detail: "Avoid precision grasping and handshakes. Encoder swap scheduled.",
  },
  {
    id: "rep-bat-07",
    assetId: "bat-07",
    openedAt: AUG(27, 13),
    openedStatus: "down",
    title: "Swollen case",
    detail: "Do not charge. Bagged and marked for disposal.",
  },
  {
    id: "rep-chg-05",
    assetId: "chg-05",
    openedAt: AUG(26, 12),
    openedStatus: "down",
    title: "No output. Fuse popped twice",
    detail: "Tagged and unplugged. Do not try another fuse until the cable is inspected.",
  },
  {
    id: "rep-rc-06",
    assetId: "rc-06",
    openedAt: AUG(27, 10),
    openedStatus: "down",
    title: "Will not pair",
    detail: "Bluetooth chip likely dead. Factory reset did not help.",
  },
  {
    id: "rep-chg-01",
    assetId: "chg-01",
    openedAt: JUL(30, 16),
    resolvedAt: AUG(1, 9),
    openedStatus: "limited",
    title: "Cable strain relief cracked",
    detail: "Brick still charged, cable was a snag hazard.",
    resolution: "Replaced the cable from the spare bin.",
  },
];

